### ISSUE TITLE
install_github("cloudyr/AzureRMR") does not work without first installing AzureAuth

### ISSUE THREAD

**Issue by angusrtaylor** [cloudyr/AzureRMR#16]
devtools::install_github(
  "cloudyr/AzureRMR",
  ref = "5eeb60988a2079b6b320af8df306c4fad802c13c"
)

fails with:

ERROR: dependency ‘AzureAuth’ is not available for package ‘AzureRMR’
* removing ‘/data/home/anta/R/x86_64-pc-linux-gnu-library/3.4/AzureRMR’
Installation failed: Command failed (1)

Can you automatically install AzureAuth when installing AzureRMR?

**Comment by Hong-Revo** [comment]
I don't get that error. Maybe try again? I recently submitted an update to AzureAuth so install_github may have gotten confused.

Also, you don't need to install from Github; regular install.packages should work. If you're using MRO you'll have to set your repo to CRAN though.

```r
options(repos="https://cloud.r-project.org")
install.packages("AzureRMR")  # also installs AzureAuth
```

**Comment by Hong-Revo** [comment]
Also, why install from a fixed ref?

**Comment by angusrtaylor** [comment]
I'm installing from a fixed ref to pin the version and avoid breaking changes. I can do the same by using an MRAN snapshot which I'll do now the package is now on CRAN.

I do not get this issue when using the CRAN version. I tried again and still get it when using install_github(). But this is no longer a problem for me so feel free to close.

**Comment by Hong-Revo** [comment]
Yeah, that sounds more like a bug in install_github.
